packages:
  - workflow
  - model
  - ui
  - test
  - liabilities-calc-script
  - block

catalog:
  "@platforma-sdk/model": ^1.29.12
  "@platforma-sdk/ui-vue": ^1.29.12
  "@platforma-sdk/workflow-tengo": ^4.1.1
  "@platforma-sdk/block-tools": ^2.5.37
  "@platforma-sdk/test": ^1.29.12
  "@platforma-sdk/tengo-builder": ^2.1.0
  "@platforma-sdk/package-builder": ^2.15.6
  "@platforma-sdk/eslint-config": ^1.0.3


  "@platforma-open/milaboratories.runenv-python-3": ^1.1.9
  
  "vue": ^3.5.12
  "vue-tsc": ^2.1.6
  
  "typescript": ~5.5.4
  "tsup": ~8.3.5
  "turbo": ^2.2.3

  "vite": ^5.4.11
  "vitest": ^2.1.8
  "@vitejs/plugin-vue": ^5.1.4

  "@changesets/cli": ^2.28.1
