packages:
  - workflow
  - model
  - ui
  - test
  - liabilities-calc-script
  - block

catalog:
  "@platforma-sdk/model": ^1.45.0
  "@platforma-sdk/ui-vue": ^1.45.5
  "@platforma-sdk/workflow-tengo": ^5.6.2
  "@platforma-sdk/block-tools": ^2.6.21
  "@platforma-sdk/test": ^1.45.9
  "@platforma-sdk/tengo-builder": ^2.3.3
  "@platforma-sdk/package-builder": ^3.10.6
  "@platforma-sdk/eslint-config": ^1.1.0
  "@platforma-sdk/blocks-deps-updater": ^2.0.0

  "@platforma-open/milaboratories.runenv-python-3": ^1.7.5

  "@vueuse/core": ^13.3.0
  "vue": ^3.5.13
  "vue-tsc": ^2.2.10
  
  "typescript": ~5.5.4
  "tsup": ~8.3.5
  "turbo": ^2.5.5

  "vite": ^6.2.4
  "vitest": ^2.1.8
  "@vitejs/plugin-vue": ^5.2.4

  "eslint": ^9.27.0

  "@changesets/cli": ^2.29.5
