packages:
  - workflow
  - model
  - ui
  - liabilities-calc-script
  - block

catalog:
  # SDK packages - EXACT VERSIONS (no ^ or ~)
  '@milaboratories/ts-builder': 1.2.3
  '@milaboratories/ts-configs': 1.2.0
  '@platforma-sdk/workflow-tengo': 5.8.0
  '@platforma-sdk/model': 1.52.3
  '@platforma-sdk/ui-vue': 1.52.3
  '@platforma-sdk/tengo-builder': 2.4.11
  '@platforma-sdk/package-builder': 3.11.0
  '@platforma-sdk/block-tools': 2.6.31
  '@platforma-sdk/eslint-config': 1.2.0
  '@platforma-sdk/test': 1.51.6
  '@milaboratories/helpers': 1.13.0

  # Block-specific dependencies
  "@platforma-open/milaboratories.runenv-python-3": ^1.4.9

  # Common dependencies - can use ^ or ~
  'vue': ^3.5.24
  '@vueuse/core': ^13.6.0
  'typescript': ~5.6.3
  'turbo': ^2.6.3
  'vitest': ^4.0.7
  'shx': ^0.4.0
  'eslint': ^9.25.1
  '@changesets/cli': ^2.29.8
