packages:
  - workflow
  - model
  - ui
  - test
  - liabilities-calc-script
  - block

catalog:
  "@platforma-sdk/model": ^1.42.20
  "@platforma-sdk/ui-vue": ^1.42.20
  "@platforma-sdk/workflow-tengo": ^5.0.2
  "@platforma-sdk/block-tools": ^2.5.83
  "@platforma-sdk/test": ^1.42.20
  "@platforma-sdk/tengo-builder": ^2.1.15
  "@platforma-sdk/package-builder": ^2.16.4
  "@platforma-sdk/eslint-config": ^1.0.3

  "@platforma-open/milaboratories.runenv-python-3": ^1.1.16

  "@vueuse/core": ^13.3.0
  "vue": ^3.5.13
  "vue-tsc": ^2.2.10
  
  "typescript": ~5.5.4
  "tsup": ~8.3.5
  "turbo": ^2.5.5
  "js-yaml": ^4.1.0

  "vite": ^6.2.4
  "vitest": ^2.1.8
  "@vitejs/plugin-vue": ^5.2.4

  "eslint": ^9.27.0

  "@changesets/cli": ^2.29.5
