packages:
  - workflow
  - model
  - ui
  - test
  - liabilities-calc-script
  - block

catalog:
  "@platforma-sdk/model": ^1.33.17
  "@platforma-sdk/ui-vue": ^1.33.17
  "@platforma-sdk/workflow-tengo": ^4.7.2
  "@platforma-sdk/block-tools": ^2.5.54
  "@platforma-sdk/test": ^1.33.17
  "@platforma-sdk/tengo-builder": ^2.1.9
  "@platforma-sdk/package-builder": ^2.16.0
  "@platforma-sdk/eslint-config": ^1.0.3

  "@platforma-open/milaboratories.runenv-python-3": ^1.1.14
  
  "vue": ^3.5.12
  "vue-tsc": ^2.2.10
  
  "typescript": ~5.5.4
  "tsup": ~8.3.5
  "turbo": ^2.5.4
  "js-yaml": ^4.1.0

  "vite": ^5.4.11
  "vitest": ^2.1.8
  "@vitejs/plugin-vue": ^5.2.4

  "eslint": ^9.27.0

  "@changesets/cli": ^2.29.4
